POST http://localhost:5000/v1/students HTTP/1.1
content-type: application/json

{
    "firstName": "Foo",
    "lastName": "Bar",
    "scores": {
        "testId": {
            "pointsScored": 100.0,
            "isPostscript": false
        }
    }
}

###

POST http://localhost:5000/v1/exams HTTP/1.1
content-type: application/json

{
    "name": "Ex4711",
    "maxPoints": 101.5,
    "gradingScale": {
        "A": 90.0,
        "B": 80.0,
        "C": 70.0,
        "D": 60.0,
        "E": 50.0,
        "F": 0.0
    }
}