server:
    port: 5000
spring:
    data:
        mongodb:
            uri: <MONGO_DB_CREDENTIALS>
            database: classplanner_beta
        rest:
            base-path: /v1
            default-page-size: 100000
    hateoas:
        use-hal-as-default-json-media-type: false